name: GitHub Actions

on: 
  push:
    branches:
      - 'main'
    paths-ignore: 
    - '.github/**'
  pull_request:
    branches:
    - 'main'
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello ${github.actor}